### PR TITLE
Update NRW colours for 2024

### PR DESCRIPTION
**Pull request by metrophil**
- add new lines RE41, RE62 [new line RB37 could not yet be added bc it's not in Hafas yet]
- edit operator for RE16, RB46, RB91, S7
- fix RE57
- fix S-Bahn colours from better source

Please only merge this on or after 10 December 2023

### CODE REVIEW

**Comment by bendix-dev** [comment]
When you change the operator the line icons would disappear for old check ins. I think you should rather duplicate those line entries.

**Comment by marhei** [comment]
I don't think it's a good idea to leave outdated data in the csv. There are already conflicts between different regions with the same line names and operators, which would only increase this problem.

**Review by marhei — APPROVED** [review]

**Comment by fzakfeld** [comment]
I think it is a bad idea to remove styles from historical checkins. Perhaps you should add a "valid from/to" field?

There is no icon for Hamburg S11 etc anymore.

**Comment by jheubuch** [comment]
> I think it is a bad idea to remove styles from historical checkins. Perhaps you should add a "valid from/to" field?
> 
> There is no icon for Hamburg S11 etc anymore.

As this is not a collection of line icons just for Träwelling check-ins (it should be a generally usable dataset), I don't think that it is useful to collect historical data.

Nevertheless please use Discussions or Issues for topics like that. A merged merge request is not the right place to discuss specification changes 😅

**Pull request merged**
