### PR TITLE
Add S-Bahn Dresden

### PR DESCRIPTION
**Pull request by Unterwerk**
S-Bahn Dresden added

### CODE REVIEW

**Comment by jheubuch** [comment]
Hi!
Thanks for your contribution.
Can we get a source (just a link etc) from where you extracted the color data?

**Comment by Unterwerk** [comment]
https://assets.static-bahn.de/dam/jcr:5b9c05ce-1bd8-46f7-9b99-4445807baa48/246507-327552.pdf

**Comment by MrKrisKrisu** [comment]
> https://assets.static-bahn.de/dam/jcr:5b9c05ce-1bd8-46f7-9b99-4445807baa48/246507-327552.pdf

Thanks! :) But can you add this to the sources.json instead?

**Review by MrKrisKrisu — CHANGES_REQUESTED** [review]
> https://assets.static-bahn.de/dam/jcr:5b9c05ce-1bd8-46f7-9b99-4445807baa48/246507-327552.pdf

Thanks! :) But can you add this to the sources.json instead?

**Review by jheubuch — APPROVED** [review]

**Review by jheubuch — APPROVED** [review]

**Pull request merged**
